# Generated by Django 2.2.4 on 2019-08-31 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_details',
            name='City',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='personal_details',
            name='Country',
            field=models.CharField(max_length=30),
        ),
    ]
